app:
  image: nucleos/proton
  cpu_shares: 5
  mem_limit: 224288000
  volumes:
    - "./api:/app/api"
    - "./test:/app/test"
    - "./.tmp:/app/.tmp"
    - "./config:/app/config"
  ports:
    - "8443:8443"
  links:
    - db
db:
  image: mongo:latest
  cpu_shares: 5
  mem_limit: 224288000
